apiVersion: v1
kind: Service
metadata:
  name: expensetracker
spec:
  selector:
    app: expensetracker
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer  # This makes the service accessible externally