apiVersion: v1
kind: Service
metadata:
  name: expensetracker
  labels:
    app: expensetracker
spec:
  selector:
    app: expensetracker
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort 