apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensetracker
  template:
    metadata:
      labels:
        app: expensetracker
    spec:
      containers:
      - name: expensetracker
        image: snehcreate/expensetracker_v3
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
        - name: SPRING_DATASOURCE_PASSWORD
          value: Test@123