apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-pvc.yml
  - mysql-deployment.yml
  - mysql-service.yml
  - app-deployment.yml
  - app-service.yml

commonLabels:
  app.kubernetes.io/managed-by: argocd